# Generated by Django 3.2.3 on 2021-05-28 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=200, null=True)),
                ('birth_date', models.DateField(null=True)),
                ('classification', models.CharField(choices=[('NonDemented', 'NonDemented'), ('MildDemented', 'MildDemented'), ('ModerateDemented', 'ModerateDemented'), ('VeryMildDemented', 'VeryMildDemented')], max_length=20)),
                ('data', models.JSONField(null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
