# Generated by Django 3.2.3 on 2021-05-28 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
