# Generated by Django 3.2.3 on 2021-05-29 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_patient_updated_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ('first_name',)},
        ),
    ]
