# Generated by Django 3.2.3 on 2021-05-29 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin User'), ('doctor', 'Doctor User'), ('guest', 'Staff User')], default='doctor', max_length=10, null=True),
        ),
    ]
