# Generated by Django 3.2.3 on 2021-05-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_patient_is_dm_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='is_dm_confirmed',
            field=models.BooleanField(null=True),
        ),
    ]
