# Generated by Django 3.2.3 on 2021-05-31 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210531_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='area',
            field=models.CharField(choices=[('P', 'Pneumology'), ('N', 'Neurology'), ('U', 'Urology')], max_length=200, null=True),
        ),
    ]
