# Generated by Django 3.2.3 on 2021-05-31 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_user_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_agreements',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
