# Generated by Django 3.2.3 on 2021-05-31 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210531_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_agreements',
            field=models.CharField(default='f', max_length=1),
        ),
    ]
