# Generated by Django 3.2.3 on 2021-05-31 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_user_is_agreements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_agreements',
            field=models.BooleanField(default=False),
        ),
    ]
