# Generated by Django 3.2.3 on 2021-05-31 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_patient_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ('updated_date',)},
        ),
    ]
