# Generated by Django 3.2.3 on 2021-05-31 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_patient_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ('-updated_date',)},
        ),
    ]
